---
name:  EC2 Docker - To Deploy Hello World app from ECR
on:
  push:
    branches: [ main, feature/** ]
    paths:
        - 'terraform/image-deploy-to-ec2/**'
jobs:
  build-and-push:
    name: hello-world-image-deploy
    runs-on: [ self-hosted, Linux ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Configure AWS credentials from AWS account
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-region: eu-west-2
    # - run: aws sts get-caller-identity

    # - name: terraform init
    #   run: |
    #     cd ./terraform/container-image-deploy-ec2 && make init

    # - name: terraform validate
    #   run: |
    #     cd ./terraform/container-image-deploy-ec2 && make validate

    # - name: terraform plan
    #   run: |
    #     cd ./terraform/container-image-deploy-ec2 && make plan

#    - uses: trstringer/manual-approval@v1
#      with:
#        secret: ${{ github.TOKEN }}
#        approvers: <approvers_name>

    # - name: terraform apply
    #   run: |
    #     cd ./terraform/container-image-deploy-ec2 && make apply
