---
name:  App team1 - AWS ECR
on:
  push:
    branches: [ main, feature/** ]
    paths:
      - 'hello-world/**'
jobs:
  build-and-push:
    name: deploy-private-ecr-eu2
    runs-on: [ self-hosted, Linux ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Configure AWS credentials from AWS account
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-region: eu-west-2
    # - run: aws sts get-caller-identity

    # - name: terraform init
    #   run: |
    #     cd ./docker-hello-world-app/ && make init

    # - name: terraform validate
    #   run: |
    #     cd ./docker-hello-world-app/ && make validate

    # - name: terraform plan
    #   run: |
    #     cd ./docker-hello-world-app/ && make plan

#    - uses: trstringer/manual-approval@v1
#      with:
#        secret: ${{ github.TOKEN }}
#        approvers: <approvers_name>

    # - name: terraform apply
    #   run: |
    #     cd ./docker-hello-world-app/ && make apply
