---
name:  Image Build Scan and Push to AWS ECR
on:
  push:
    branches: [ main, feature/** ]
    paths:
      - 'hello-world/src/**'

jobs:
  build-and-push:
    name: build-and-ImageScane-push-image
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dockerfile lint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./hello-world/ && make lint

    - name: Build the container image
      id: build-image
      env:
        DOCKER_REGISTRY: ${{ steps.login-docker.outputs.registry }}
      run: |
        cd ./hello-world/ && make build

    # - name: Run Trivy vulnerability scanner
    #   id: scan-image
    #   env:
    #     DOCKER_REGISTRY: ${{ steps.login-docker.outputs.registry }}
    #   run: |
    #     cd ./hello-world/ && make image-scan

    # - name: Push image to ECR
    #   id: push-image
    #   env:
    #     DOCKER_REGISTRY: ${{ steps.login-docker.outputs.registry }}

    #   run: |
    #     cd ./hello-world/ && make push
# ===================================================================
    # - name: Configure AWS credentials from AWS account
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-region: eu-west-2
    # - run: aws sts get-caller-identity

    # - name: terraform init
    #   run: |
    #     make init

    # - name: terraform plan
    #   run: |
    #     make plan

    # - name: terraform apply
    #   run: |
    #     make apply